export const ROOMS = [
  {
    id: 'A101',
    name: 'ห้องประชุม A101',
    building: 'อาคาร A',
    floor: 'ชั้น 1',
    capacity: 8,
    screens: 1,
    microphones: 2,
    tv: 1,
    plugs: 8,
    layout: 'Boardroom',
    equipment: ['Projector', 'Whiteboard', 'HDMI'],
    status: 'active',
  },
  {
    id: 'A102',
    name: 'ห้องประชุม A102',
    building: 'อาคาร A',
    floor: 'ชั้น 1',
    capacity: 12,
    screens: 2,
    microphones: 4,
    tv: 2,
    plugs: 12,
    layout: 'U-Shape',
    equipment: ['Projector', 'TV', 'HDMI', 'Video Conference'],
    status: 'active',
  },
  {
    id: 'A103',
    name: 'ห้องประชุม A103',
    building: 'อาคาร A',
    floor: 'ชั้น 1',
    capacity: 6,
    screens: 1,
    microphones: 1,
    tv: 1,
    plugs: 6,
    layout: 'Classroom',
    equipment: ['TV', 'Whiteboard'],
    status: 'maintenance',
  },
  {
    id: 'A201',
    name: 'ห้องประชุม A201',
    building: 'อาคาร A',
    floor: 'ชั้น 2',
    capacity: 10,
    screens: 1,
    microphones: 2,
    tv: 1,
    plugs: 10,
    layout: 'U-Shape',
    equipment: ['Projector', 'TV', 'Microphone', 'Whiteboard', 'HDMI', 'Video Conference'],
    status: 'active',
  },
  {
    id: 'A202',
    name: 'ห้องประชุม A202',
    building: 'อาคาร A',
    floor: 'ชั้น 2',
    capacity: 20,
    screens: 2,
    microphones: 6,
    tv: 2,
    plugs: 20,
    layout: 'Theater',
    equipment: ['Projector', 'TV', 'HDMI', 'Video Conference', 'Wi-Fi'],
    status: 'active',
  },
  {
    id: 'B301',
    name: 'ห้องประชุม B301',
    building: 'อาคาร B',
    floor: 'ชั้น 3',
    capacity: 15,
    screens: 1,
    microphones: 2,
    tv: 1,
    plugs: 15,
    layout: 'Classroom',
    equipment: ['Projector', 'TV', 'HDMI'],
    status: 'disabled',
  },
];

export const ALL_TAGS = [
  'HDMI',
  'Microphone',
  'Projector',
  'TV',
  'Video Conference',
  'Whiteboard',
  'Wi-Fi',
];

export const STATUS_LABELS = {
  active: 'พร้อมใช้งาน',
  maintenance: 'ซ่อมบำรุง',
  disabled: 'ปิดใช้งาน',
  confirmed: 'ยืนยันแล้ว',
  pending: 'รออนุมัติ',
  cancelled: 'ยกเลิกแล้ว',
  completed: 'เสร็จสิ้น',
};

export const INITIAL_BOOKINGS = [
  {
    id: 'b1',
    roomId: 'A201',
    roomName: 'ห้องประชุม A201',
    user: 'ณัฐวุฒิ ส.',
    date: '26 ส.ค. 2568',
    start: '10:00',
    end: '11:00',
    status: 'confirmed',
  },
  {
    id: 'b2',
    roomId: 'A102',
    roomName: 'ห้องประชุม A102',
    user: 'ปวีณา จ.',
    date: '26 ส.ค. 2568',
    start: '13:00',
    end: '14:00',
    status: 'pending',
  },
  {
    id: 'b3',
    roomId: 'A201',
    roomName: 'ห้องประชุม A201',
    user: 'ธนกร พ.',
    date: '26 ส.ค. 2568',
    start: '15:00',
    end: '16:00',
    status: 'confirmed',
  },
  {
    id: 'b4',
    roomId: 'A202',
    roomName: 'ห้องประชุม A202',
    user: 'ศิริพร ม.',
    date: '27 ส.ค. 2568',
    start: '09:00',
    end: '10:00',
    status: 'confirmed',
  },
  {
    id: 'b5',
    roomId: 'A102',
    roomName: 'ห้องประชุม A102',
    user: 'ณัฐวุฒิ ส.',
    date: '27 ส.ค. 2568',
    start: '13:00',
    end: '14:00',
    status: 'pending',
  },
  {
    id: 'b6',
    roomId: 'A101',
    roomName: 'ห้องประชุม A101',
    user: 'วีรชัย ก.',
    date: '27 ส.ค. 2568',
    start: '14:00',
    end: '15:00',
    status: 'completed',
  },
  {
    id: 'b7',
    roomId: 'A103',
    roomName: 'ห้องประชุม A103',
    user: 'อรทัย น.',
    date: '28 ส.ค. 2568',
    start: '11:00',
    end: '12:00',
    status: 'cancelled',
  },
  {
    id: 'b8',
    roomId: 'A202',
    roomName: 'ห้องประชุม A202',
    user: 'ณัฐวุฒิ ส.',
    date: '20 ส.ค. 2568',
    start: '09:00',
    end: '10:00',
    status: 'completed',
  },
  {
    id: 'b9',
    roomId: 'A101',
    roomName: 'ห้องประชุม A101',
    user: 'ณัฐวุฒิ ส.',
    date: '19 ส.ค. 2568',
    start: '14:00',
    end: '15:00',
    status: 'cancelled',
  },
  {
    id: 'b10',
    roomId: 'A201',
    roomName: 'ห้องประชุม A201',
    user: 'วีรชัย ก.',
    date: '29 ส.ค. 2568',
    start: '10:00',
    end: '11:00',
    status: 'pending',
  },
];

const THAI_MONTHS_SHORT = [
  'ม.ค.',
  'ก.พ.',
  'มี.ค.',
  'เม.ย.',
  'พ.ค.',
  'มิ.ย.',
  'ก.ค.',
  'ส.ค.',
  'ก.ย.',
  'ต.ค.',
  'พ.ย.',
  'ธ.ค.',
];

export function formatThaiDate(isoDate) {
  if (!isoDate) return '';
  const [year, month, day] = isoDate.split('-').map(Number);
  if (!year || !month || !day) return isoDate;
  return `${day} ${THAI_MONTHS_SHORT[month - 1]} ${year + 543}`;
}
